import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class Lekarz extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    
    public Lekarz() {
        initComponents();
        setLocationRelativeTo(null);
        txtID.setText(String.valueOf(ID()));        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtImie = new javax.swing.JTextField();
        txtNazwisko = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        txtPesel = new javax.swing.JTextField();
        txtNumerTel = new javax.swing.JTextField();
        txtKwalifikacje = new javax.swing.JTextField();
        txtSpecializacja = new javax.swing.JTextField();
        cmbGK = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbPlec = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnNowy = new javax.swing.JButton();
        btnZapisz = new javax.swing.JButton();
        btnUsun = new javax.swing.JButton();
        btnNadpisz = new javax.swing.JButton();
        Lekarze = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lekarz\n");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lekarz"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Imię");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nazwisko");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Adres");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pesel");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Numer tel.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kwalifikacje");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Specializacja");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Grupa krwi");

        txtID.setEditable(false);
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPesel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeselKeyTyped(evt);
            }
        });

        txtNumerTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeselKeyTyped(evt);
            }
        });

        cmbGK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        cmbGK.setSelectedIndex(-1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Płeć");

        cmbPlec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mężczyzna", "Kobieta" }));
        cmbPlec.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumerTel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbGK, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPlec, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtKwalifikacje, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtAdres)
                    .addComponent(txtNazwisko)
                    .addComponent(txtImie)
                    .addComponent(txtSpecializacja))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNumerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKwalifikacje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSpecializacja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbPlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbGK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNowy.setText("Reset");
        btnNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNowyActionPerformed(evt);
            }
        });

        btnZapisz.setText("Zapisz");
        btnZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszActionPerformed(evt);
            }
        });

        btnUsun.setText("Usun");
        btnUsun.setEnabled(false);
        btnUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunActionPerformed(evt);
            }
        });

        btnNadpisz.setText("Nadpisz");
        btnNadpisz.setEnabled(false);
        btnNadpisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadpiszActionPerformed(evt);
            }
        });

        Lekarze.setText("Lekarze");
        Lekarze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LekarzeActionPerformed(evt);
            }
        });

        jButton1.setText("Zamknij");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNowy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZapisz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNadpisz, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lekarze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNadpisz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lekarze, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zdjecia/4.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int ID()
    {
    int ID=1;
        con=Polaczenie.ConnectDB();
         String sql= "SELECT LEKARZID FROM SZPITAL_DB.LEKARZ WHERE LEKARZID = (SELECT MAX(LEKARZID) FROM SZPITAL_DB.LEKARZ)";
    try    
      {
          pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
           if(rs.next()){
        String add1=rs.getString("LEKARZID");
        int IDLast = Integer.parseInt(add1);
        ID = IDLast+1;
           }
      }
    catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
   }
    return ID;      
    }
    
    private void Reset()
{
    txtID.setText(String.valueOf(ID()));
    txtImie.setText("");
    txtNazwisko.setText("");
    txtPesel.setText("");
    txtAdres.setText("");
    txtKwalifikacje.setText("");
    txtNumerTel.setText("");
    txtSpecializacja.setText("");
    cmbGK.setSelectedIndex(-1);
    cmbPlec.setSelectedIndex(-1);
    btnZapisz.setEnabled(true);
    btnNadpisz.setEnabled(false);
    btnUsun.setEnabled(false);
    txtID.requestDefaultFocus();

}
    private void btnNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNowyActionPerformed
        Reset();
    }//GEN-LAST:event_btnNowyActionPerformed

    private void btnZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszActionPerformed
        try{
            con=Polaczenie.ConnectDB();
       //     if (txtID.getText().equals("")) {
       //         JOptionPane.showMessageDialog( this, "Podaj ID","Błąd !", JOptionPane.ERROR_MESSAGE);
       //         return;

       //     }
            if (txtImie.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj imię","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (txtNazwisko.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj nazwisko","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtAdres.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter address","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
           if (txtPesel.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj PESEL","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
         
            if (txtKwalifikacje.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj kwalifikacje","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtSpecializacja.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj specializację","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
             if (cmbPlec.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj płeć","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cmbGK.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj grupę krwi","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
   Statement stmt;
       stmt= con.createStatement();
       String sql1="Select LEKARZID from SZPITAL_DB.LEKARZ where LEKARZID= '" + txtID.getText() + "'";
      rs=stmt.executeQuery(sql1);
      if(rs.next()){
        JOptionPane.showMessageDialog( this, "ID jest zajęte","Błąd !", JOptionPane.ERROR_MESSAGE);
        txtID.setText("");
        txtID.requestDefaultFocus();
       return;
      }
      String query = "{CALL SZPITAL_DB.zapisz_lekarz(?,?,?,?,?,?,?,?,?,?)}" ;
            CallableStatement cst = con.prepareCall(query); 
            cst.setString(1,txtID.getText());
            cst.setString(2,txtImie.getText());
            cst.setString(3,txtNazwisko.getText());
            cst.setString(4,txtAdres.getText());
            cst.setString(5,txtPesel.getText());
            cst.setString(6,txtNumerTel.getText());
            cst.setString(7,txtKwalifikacje.getText());
            cst.setString(8,txtSpecializacja.getText());
            cst.setString(9, (String) cmbPlec.getSelectedItem());
            cst.setString(10, (String) cmbGK.getSelectedItem());
            cst.execute();
            cst.close();     
            
            JOptionPane.showMessageDialog(this,"Zapisano !","Sukces !",JOptionPane.INFORMATION_MESSAGE);
            btnZapisz.setEnabled(false);

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnZapiszActionPerformed

    private void btnUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunActionPerformed
        try{
            int P = JOptionPane.showConfirmDialog(null,"Czy jesteś pewny usunięcia ?","Potwierdzenie",JOptionPane.YES_NO_OPTION);
            if (P==0)
            {
               String query = "{CALL SZPITAL_DB.usun_lekarz(?)}" ;
            CallableStatement cst = con.prepareCall(query); 
            cst.setString(1,txtID.getText());
            cst.execute();
            cst.close();     
            JOptionPane.showMessageDialog(this,"Usunięto !","Potwierdzenie",JOptionPane.INFORMATION_MESSAGE);

                Reset();
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnUsunActionPerformed

    private void btnNadpiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadpiszActionPerformed
        try{
            con=Polaczenie.ConnectDB();
            String sql= "update SZPITAL_DB.LEKARZ set LEKARZIMIE='"+ txtImie.getText() + "',LEKARZNAZWISKO='"+ txtNazwisko.getText() + "',NUMERTEL='"+ txtNumerTel.getText() + "',PESEL='"+ txtPesel.getText() + "',KWALIFIKACJE='"+ txtKwalifikacje.getText() + "',SPECIALIZACJA='"+ txtSpecializacja.getText() + "',PLEC='" + cmbPlec.getSelectedItem() + "',GK='"+ cmbGK.getSelectedItem() + "',ADRES='" + txtAdres.getText() + "' where LEKARZID='" + txtID.getText() + "'";

           pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Nadpisao","Potwierdzenie !",JOptionPane.INFORMATION_MESSAGE);
            btnNadpisz.setEnabled(false);

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnNadpiszActionPerformed

    private void LekarzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LekarzeActionPerformed
     this.hide();
     LekarzTabela frm=new LekarzTabela();
     frm.setVisible(true);
    }//GEN-LAST:event_LekarzeActionPerformed

    private void txtPeselKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPeselKeyTyped
       char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
    }//GEN-LAST:event_txtPeselKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lekarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lekarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lekarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lekarz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lekarz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lekarze;
    public javax.swing.JButton btnNadpisz;
    private javax.swing.JButton btnNowy;
    public javax.swing.JButton btnUsun;
    public javax.swing.JButton btnZapisz;
    public javax.swing.JComboBox cmbGK;
    public javax.swing.JComboBox cmbPlec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtAdres;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtImie;
    public javax.swing.JTextField txtKwalifikacje;
    public javax.swing.JTextField txtNazwisko;
    public javax.swing.JTextField txtNumerTel;
    public javax.swing.JTextField txtPesel;
    public javax.swing.JTextField txtSpecializacja;
    // End of variables declaration//GEN-END:variables
}
