import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Date;

public class Login extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;

    public static String login;
    public static String terazLogowanie;
    
    
    public Login() {
        
        initComponents();
        setLocationRelativeTo(null);
        setIco();
                 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSplitPane1 = new javax.swing.JSplitPane();
        txtLogin = new javax.swing.JTextField();
        txtHaslo = new javax.swing.JPasswordField();
        btnZaloguj = new javax.swing.JButton();
        btnWyjscie = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logowanie");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginMouseClicked(evt);
            }
        });
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        txtHaslo.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        txtHaslo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHaslo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHasloKeyPressed(evt);
            }
        });

        btnZaloguj.setBackground(new java.awt.Color(204, 204, 204));
        btnZaloguj.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnZaloguj.setText("Zaloguj");
        btnZaloguj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZalogujMouseClicked(evt);
            }
        });
        btnZaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZalogujActionPerformed(evt);
            }
        });

        btnWyjscie.setBackground(new java.awt.Color(204, 204, 204));
        btnWyjscie.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        btnWyjscie.setText("Wyjście");
        btnWyjscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWyjscieActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zdjecia/hospital.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zdjecia/login-icon-3049.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zdjecia/user-login-human-man-body-512.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jButton1.setText("Demo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHaslo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnZaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnWyjscie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLogin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHaslo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtLoginMouseClicked

    private void btnZalogujMouseClicked(java.awt.event.MouseEvent evt) { 
     
    if (txtLogin.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Podaj login !","Błąd !", JOptionPane.ERROR_MESSAGE);
           return;
            
            }
    String Password= String.valueOf(txtHaslo.getPassword());
        if (Password.equals("")) {
           JOptionPane.showMessageDialog( this, "Podaj hasło !","Błąd !", JOptionPane.ERROR_MESSAGE);
           return;
          
            }
      con=Polaczenie.ConnectDB();
         String sql= "select * from SZPITAL_DB.LOGOWANIE where LOGIN= '" + txtLogin.getText() + "' and HASLO ='" + txtHaslo.getText() + "'";
    try
      {
          pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
          if (rs.next()){
             this.hide();
             //status start
        String status = "null";
        con=Polaczenie.ConnectDB();
         String sql1= "select status from SZPITAL_DB.LOGOWANIE where LOGIN= '" +txtLogin.getText()+ "'";
    try
      {
          pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
           if(rs.next()){
        String add1=rs.getString("status");
          status = add1;
          
            if("admin".equals(status))
            {
             Menu frm=new Menu();
             frm.setVisible(true);
            }
            else 
            if("pacjent".equals(status))
            {
             PacjentMenu frm=new PacjentMenu();
             frm.setVisible(true);
            }
            else
                 JOptionPane.showMessageDialog( this, "Wystąpił błąd statusu twojego konta","Błąd !", JOptionPane.ERROR_MESSAGE);
           }
      }
    catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
   }
                
         //    Menu frm=new Menu();
         //    frm.setVisible(true);
             
                Date dNow = new Date();
                SimpleDateFormat ft = 
                new SimpleDateFormat ("E dd.MM.yyy 'o' HH:mm:ss ");
                terazLogowanie =ft.format(dNow);
                String sql2= "update SZPITAL_DB.LOGOWANIE set TERAZLOGOWANIE='"+ft.format(dNow)+"' where LOGIN='" + txtLogin.getText() + "'";
                pst=con.prepareStatement(sql2);
                pst.execute();
          }
          else{
              
            JOptionPane.showMessageDialog(null, "Błędne dane !","Błąd !",JOptionPane.ERROR_MESSAGE);
          }
      }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }                                     
    }                                  

    private void btnWyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWyjscieActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnWyjscieActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
    }//GEN-LAST:event_formWindowOpened

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnZalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZalogujActionPerformed
      
    }//GEN-LAST:event_btnZalogujActionPerformed

    private void txtHasloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHasloKeyPressed
        login = txtLogin.getText();
   
    // JOptionPane.showMessageDialog(null,ft.format(dNow));

        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            con=Polaczenie.ConnectDB();
            String sql= "select * from SZPITAL_DB.LOGOWANIE where LOGIN= '" + txtLogin.getText() + "' and HASLO ='" + txtHaslo.getText() + "'";
            try
            {
                pst=con.prepareStatement(sql);
                rs= pst.executeQuery();
                
                 if (rs.next()){
             this.hide();
             //status start
        String status = "null";
        con=Polaczenie.ConnectDB();
         String sql1= "select status from SZPITAL_DB.LOGOWANIE where LOGIN= '" +txtLogin.getText()+ "'";
    try
      {
          pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
           if(rs.next()){
        String add1=rs.getString("status");
          status = add1;
          
            if("admin".equals(status))
            {
             Menu frm=new Menu();
             frm.setVisible(true);
            }
            else 
            if("pacjent".equals(status))
            {
             PacjentMenu frm=new PacjentMenu();
             frm.setVisible(true);
            }
            else
            if("lekarz".equals(status))
            {
         //    LekarzMenu frm=new LekarzMenu();
         //    frm.setVisible(true);
            }
            else
                 JOptionPane.showMessageDialog( this, "Wystąpił błąd statusu twojego konta","Błąd !", JOptionPane.ERROR_MESSAGE);
           }
      }
    catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
   }
                
         //    Menu frm=new Menu();
         //    frm.setVisible(true);
                Date dNow = new Date();
                SimpleDateFormat ft = 
                new SimpleDateFormat ("E dd.MM.yyy 'o' HH:mm:ss ");
                terazLogowanie =ft.format(dNow);
                String sql2= "update SZPITAL_DB.LOGOWANIE set TERAZLOGOWANIE='"+ft.format(dNow)+"' where LOGIN='" + txtLogin.getText() + "'";
                pst=con.prepareStatement(sql2);
                pst.execute();

                }
                else{

                    JOptionPane.showMessageDialog(null, "Błędne dane  !","Błąd !",JOptionPane.ERROR_MESSAGE);
                    txtLogin.setText("");
                    txtHaslo.setText("");
                    txtLogin.requestDefaultFocus();
                }
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_txtHasloKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // txtLogin.setText("admin");
    // txtHaslo.setText("12345");
        demo frm= new demo();
     frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWyjscie;
    private javax.swing.JButton btnZaloguj;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JPasswordField txtHaslo;
    public javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables

    private void setIco() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Zdjecia/443775.png")));
    }
}
