
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Oddzial extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    

    public Oddzial() {
        initComponents();
         con= Polaczenie.ConnectDB();
        Get_Data();
        setLocationRelativeTo(null);

    }
    private void Reset()
{
    txtNazwa.setText("");
    cmbRodzaj.setSelectedIndex(-1);
    txtLiczba.setText("");
    btnZapisz.setEnabled(true);
    btnUsun.setEnabled(false);
    btnNadpisz.setEnabled(false);
    txtNazwa.requestDefaultFocus();
    Get_Data();
}
 private void Get_Data(){
          String sql="select NAZWAODDZIALU as Nazwa ,RODZAJODDZIALU as Rodzaj ,LICZBALOZEK as Łóżka  from SZPITAL_DB.ODDZIAL";
          try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tabela.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNazwa = new javax.swing.JTextField();
        cmbRodzaj = new javax.swing.JComboBox();
        txtLiczba = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNowy = new javax.swing.JButton();
        btnZapisz = new javax.swing.JButton();
        btnNadpisz = new javax.swing.JButton();
        btnUsun = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oddział");
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(590, 530));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacje"));

        jLabel1.setText("Nazwa:");

        jLabel2.setText("Rodzaj:");

        jLabel3.setText("Liczba łóżek:");

        txtNazwa.setName(""); // NOI18N
        txtNazwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazwaActionPerformed(evt);
            }
        });

        cmbRodzaj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ratunkowy", "Chirurgii ", "Dzieciecy", "Neurologiczny", "Psychiatryczny", "Ortopedyczny", "Wewnetrzny", "Intensywnej opieki" }));

        txtLiczba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLiczbaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNazwa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLiczba, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbRodzaj, javax.swing.GroupLayout.Alignment.LEADING, 0, 154, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRodzaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nazwa", "Rodzaj", "Liczba łóżek"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnNowy.setFont(new java.awt.Font("Andale Mono", 0, 12)); // NOI18N
        btnNowy.setText("Nowy");
        btnNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNowyActionPerformed(evt);
            }
        });

        btnZapisz.setFont(new java.awt.Font("Andale Mono", 0, 12)); // NOI18N
        btnZapisz.setText("Zapisz");
        btnZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszActionPerformed(evt);
            }
        });

        btnNadpisz.setFont(new java.awt.Font("Andale Mono", 0, 12)); // NOI18N
        btnNadpisz.setText("Nadpisz");
        btnNadpisz.setEnabled(false);
        btnNadpisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadpiszActionPerformed(evt);
            }
        });

        btnUsun.setFont(new java.awt.Font("Andale Mono", 0, 12)); // NOI18N
        btnUsun.setText("Usuń");
        btnUsun.setEnabled(false);
        btnUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zdjecia/hospital-ward.jpg"))); // NOI18N

        jButton1.setText("Zamknij");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNadpisz, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNadpisz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNowyActionPerformed
        Reset();
    }//GEN-LAST:event_btnNowyActionPerformed

    private void btnZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszActionPerformed
        try{
            con=Polaczenie.ConnectDB();
            if (txtNazwa.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj nazwę oddziału","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cmbRodzaj.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Wybierz rodzaj oddziału","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtLiczba.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj liczbę łóżek","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Statement stmt;
            stmt= con.createStatement();
            String sql1="Select nazwaoddzialu from SZPITAL_DB.oddzial where nazwaoddzialu= '" + txtNazwa.getText() + "'";
            rs=stmt.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog( this, "Nazwa jest już zajęta","Błąd !", JOptionPane.ERROR_MESSAGE);
                txtNazwa.setText("");
                txtNazwa.requestDefaultFocus();
                return;
            }
          
            String query = "{CALL SZPITAL_DB.zapisz_oddzial(?,?,?)}" ;
            CallableStatement cst = con.prepareCall(query); 
            cst.setString(1,txtNazwa.getText());
            cst.setString(2, (String) cmbRodzaj.getSelectedItem());
            cst.setString(3,txtLiczba.getText());
            cst.execute();
            cst.close();
            
            JOptionPane.showMessageDialog(this,"Zapisano","Potwierdzenie",JOptionPane.INFORMATION_MESSAGE);
            btnZapisz.setEnabled(false);
            Get_Data();
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnZapiszActionPerformed

    private void btnNadpiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadpiszActionPerformed
        try{
            con=Polaczenie.ConnectDB();
            String sql= "update SZPITAL_DB.ODDZIAL set rodzajoddzialu='"+ cmbRodzaj.getSelectedItem() + "',liczbalozek=" + txtLiczba.getText() + " where nazwaoddzialu='" + txtNazwa.getText() + "'";
            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Nadpisano","Potwierdzenie",JOptionPane.INFORMATION_MESSAGE);
            btnNadpisz.setEnabled(false);
            Get_Data();
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnNadpiszActionPerformed

    private void btnUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunActionPerformed
        try
        {
            int P = JOptionPane.showConfirmDialog(null,"Czy jesteś pewny usunięta ? ","Potwierdzenie",JOptionPane.YES_NO_OPTION);
            if (P==0)
            {
               String query = "{CALL SZPITAL_DB.usun_oddzial(?)}" ;
            CallableStatement cst = con.prepareCall(query); 
            cst.setString(1,txtNazwa.getText());
            cst.execute();
            cst.close();     
            JOptionPane.showMessageDialog(this,"Usunięto !","Potwierdzenie",JOptionPane.INFORMATION_MESSAGE);

                Reset();
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }

    }//GEN-LAST:event_btnUsunActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        try{
            con=Polaczenie.ConnectDB();
            int row= tabela.getSelectedRow();
            String table_click= tabela.getModel().getValueAt(row, 0).toString();
            String sql= "select * from SZPITAL_DB.ODDZIAL where nazwaoddzialu = '" + table_click + "'";
            pst=con.prepareStatement(sql);
            rs=  pst.executeQuery();
            if(rs.next()){

                String add1=rs.getString("nazwaoddzialu");
                txtNazwa.setText(add1);
                String add2=rs.getString("rodzajoddzialu");
                cmbRodzaj.setSelectedItem(add2);
                int add3 = rs.getInt("liczbalozek");
                String add4= Integer.toString(add3);
                txtLiczba.setText(add4);
                btnNadpisz.setEnabled(true);
                btnUsun.setEnabled(true);
                btnZapisz.setEnabled(false);

            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void txtLiczbaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLiczbaKeyTyped
       char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
    }//GEN-LAST:event_txtLiczbaKeyTyped

    private void txtNazwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazwaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazwaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oddzial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oddzial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oddzial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oddzial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oddzial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNadpisz;
    private javax.swing.JButton btnNowy;
    private javax.swing.JButton btnUsun;
    private javax.swing.JButton btnZapisz;
    private javax.swing.JComboBox cmbRodzaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtLiczba;
    private javax.swing.JTextField txtNazwa;
    // End of variables declaration//GEN-END:variables
}
