
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.security.SecureRandom;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.JOptionPane;


public class Pacjent extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
public static String tmpLogin;
public static String tmpHaslo;

    public Pacjent() {
        initComponents();
        setLocationRelativeTo(null);
        txtIDPacjenta.setText(String.valueOf(ID()));        
    }
private void Reset()
{
    txtIDPacjenta.setText(String.valueOf(ID()));
    txtImie.setText("");
    txtNazwisko.setText("");
    txtPesel.setText("");
    txtAdres.setText("");
    txtWiek.setText("");
    txtNumerTel.setText("");
    txtUwagi.setText("");
    cmbGrupaKrwi.setSelectedIndex(-1);
    cmbPlec.setSelectedIndex(-1);
    btnZapisz.setEnabled(true);
    btnNadpisz.setEnabled(false);
    btnUsun.setEnabled(false);
    txtPesel.setEnabled(true);
    txtIDPacjenta.requestDefaultFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDPacjenta = new javax.swing.JTextField();
        txtImie = new javax.swing.JTextField();
        txtNazwisko = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        txtWiek = new javax.swing.JTextField();
        txtNumerTel = new javax.swing.JTextField();
        cmbGrupaKrwi = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbPlec = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtPesel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUwagi = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnNowy = new javax.swing.JButton();
        btnZapisz = new javax.swing.JButton();
        btnUsun = new javax.swing.JButton();
        btnNadpisz = new javax.swing.JButton();
        btnPacjenci = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pacjent");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacje"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Imię");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nazwisko");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Adres");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pesel");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Numer tel.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Grupa krwi");

        txtIDPacjenta.setEditable(false);
        txtIDPacjenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtWiek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWiekKeyTyped(evt);
            }
        });

        txtNumerTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeselKeyTyped(evt);
            }
        });

        cmbGrupaKrwi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        cmbGrupaKrwi.setSelectedIndex(-1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Płeć");

        cmbPlec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mężczyzna", "Kobieta" }));
        cmbPlec.setSelectedIndex(-1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Wiek");

        txtPesel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeselKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Uwagi");

        txtUwagi.setColumns(20);
        txtUwagi.setRows(5);
        jScrollPane1.setViewportView(txtUwagi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtImie)
                        .addComponent(txtNazwisko, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(txtAdres, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(txtNumerTel)
                        .addComponent(txtIDPacjenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbGrupaKrwi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPlec, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWiek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDPacjenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNumerTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWiek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbGrupaKrwi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNowy.setText("Nowy");
        btnNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNowyActionPerformed(evt);
            }
        });

        btnZapisz.setText("Zapisz");
        btnZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapiszActionPerformed(evt);
            }
        });

        btnUsun.setText("Usuń");
        btnUsun.setEnabled(false);
        btnUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsunActionPerformed(evt);
            }
        });

        btnNadpisz.setText("Nadpisz");
        btnNadpisz.setEnabled(false);
        btnNadpisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadpiszActionPerformed(evt);
            }
        });

        btnPacjenci.setText("Pacjenci");
        btnPacjenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacjenciActionPerformed(evt);
            }
        });

        jButton1.setText("Zamknij");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPacjenci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNadpisz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZapisz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNowy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnZapisz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNadpisz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPacjenci, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zdjecia/single-info2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

static final String AB = "0123456789";
static SecureRandom rnd = new SecureRandom();

String randomHaslo( int len ){
   StringBuilder sb = new StringBuilder( len );
   for( int i = 0; i < len; i++ ) 
      sb.append( AB.charAt( rnd.nextInt(AB.length()) ) );
   return sb.toString();
}
    
    private int ID()
    {
    int ID=1;
        con=Polaczenie.ConnectDB();
         String sql= "SELECT PACJENTID FROM SZPITAL_DB.PACJENT WHERE PACJENTID = (SELECT MAX(PACJENTID) FROM SZPITAL_DB.PACJENT)";
    try    
      {
          pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
           if(rs.next()){
        String add1=rs.getString("PACJENTID");
        int IDLast = Integer.parseInt(add1);
        ID = IDLast+1;
           }
      }
    catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
   }
    return ID;      
    }
    
    private void btnNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNowyActionPerformed
    Reset();
    }//GEN-LAST:event_btnNowyActionPerformed

    private void btnZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapiszActionPerformed
     try{
            con=Polaczenie.ConnectDB();
        //    if (txtIDPacjenta.getText().equals("")) {
        //        JOptionPane.showMessageDialog( this, "Podaj ID pacjęta !","Błąd !", JOptionPane.ERROR_MESSAGE);
        //        return;

        //    }
            if (txtImie.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj imię !","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (txtNazwisko.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj nazwisko !","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtAdres.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj adres !","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
           if (txtPesel.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj PESEL !","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
         
            if (txtWiek.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj wiek !","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
             if (cmbPlec.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj płeć!","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cmbGrupaKrwi.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Podaj grupę krwi !","Błąd !", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
          
   Statement stmt;
       stmt= con.createStatement();
       String sql1="Select PESEL from SZPITAL_DB.PACJENT where PESEL= '" + txtPesel.getText() + "'"; 
      rs=stmt.executeQuery(sql1);
      if(rs.next()){
        JOptionPane.showMessageDialog( this, "Pacjent z tym numerem PESEL istanieje w bazie","Błąd !", JOptionPane.ERROR_MESSAGE);
        txtPesel.setText("");
        txtPesel.requestDefaultFocus();
        
       return;
      }
      String query = "{CALL SZPITAL_DB.zapisz_pacjent(?,?,?,?,?,?,?,?,?,?)}" ;
            CallableStatement cst = con.prepareCall(query); 
            cst.setString(1,txtIDPacjenta.getText());
            cst.setString(2,txtImie.getText());
            cst.setString(3,txtNazwisko.getText());
            cst.setString(4,txtNumerTel.getText());
            cst.setString(5,txtPesel.getText());
            cst.setString(6,txtWiek.getText());
            cst.setString(7,txtUwagi.getText());
            cst.setString(8, (String) cmbPlec.getSelectedItem());
            cst.setString(9, (String) cmbGrupaKrwi.getSelectedItem());
            cst.setString(10,txtAdres.getText());
            cst.execute();
            cst.close();     
            
            
            // tworzenie użytkownika do logowania
            
            String haslo ="";
            haslo = randomHaslo(8);
            
            String sql= "insert into SZPITAL_DB.LOGOWANIE(LOGIN,HASLO,IMIE,STATUS,EMAIL)values('"+ txtPesel.getText() + "','"+ haslo + "','"+ txtImie.getText()+" "+txtNazwisko.getText() + "','"+ "pacjent"+ "','" + "email" + "')";
            pst=con.prepareStatement(sql);
            pst.execute();
            
            btnZapisz.setEnabled(false);
            
             JOptionPane.showMessageDialog(this,"Zapisano !","Sukces !",JOptionPane.INFORMATION_MESSAGE);
            
             tmpLogin = txtPesel.getText();
             tmpHaslo = haslo;
             
            PacjentHasloPDF frm = new PacjentHasloPDF();
            frm.setVisible(true);
            
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
             
        }
    }//GEN-LAST:event_btnZapiszActionPerformed

    private void btnUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsunActionPerformed
        try{
            int P = JOptionPane.showConfirmDialog(null,"Czy jesteś pewny usunięcia ?","Potwierdzenie",JOptionPane.YES_NO_OPTION);
            int PK=0;
            if (P==0)
            {
                String zmiennaString;
                String PESEL = txtPesel.getText();
                int a;
                
                con=Polaczenie.ConnectDB();
                String sql="{? = call SZPITAL_DB.PACJENT_USUN_PK_ERROR(?)}";
                
                CallableStatement stmt = con.prepareCall(sql);
                stmt.setString(2,PESEL);
                stmt.registerOutParameter(1,Types.VARCHAR);
                stmt.execute();
                String ile = stmt.getString(1);
                stmt.execute();
                zmiennaString = ile;
                
                a= Integer.parseInt(zmiennaString);
                
                
                if(a>=1)
                {
                 PK=1;   
                 JOptionPane.showMessageDialog(this,"Nie można usunąć ponieważ pacjent jest na oddziale","Błąd",JOptionPane.INFORMATION_MESSAGE);
                }
               
            }
            
            if (P==0 && PK==0)
            {
                //usuwanie pacjenta
                String query = "{CALL SZPITAL_DB.usun_pacjent(?)}" ;
                CallableStatement cst = con.prepareCall(query);
                cst.setString(1,txtIDPacjenta.getText());
                cst.execute();
                cst.close();
                JOptionPane.showMessageDialog(this,"Usunięto !","Potwierdzenie",JOptionPane.INFORMATION_MESSAGE);
            } 
            if (P==0 && PK==0)
            {
            //usuwanie uzytkownika do logowania
            String query = "{CALL SZPITAL_DB.usun_uzytkownik(?)}" ;
            CallableStatement cst = con.prepareCall(query); 
            cst.setString(1,txtPesel.getText());
            cst.execute();
            cst.close();
            
            Reset();
            }
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_btnUsunActionPerformed

    private void btnPacjenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacjenciActionPerformed
this.hide();
PacjentTabela frm=new PacjentTabela();
frm.setVisible(true);
    }//GEN-LAST:event_btnPacjenciActionPerformed

    private void btnNadpiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadpiszActionPerformed
 try{
            con=Polaczenie.ConnectDB();
          
            String sql= "update SZPITAL_DB.PACJENT set PACJENTIMIE='"+ txtImie.getText() + "',PACJENTNAZWISKO='"+ txtNazwisko.getText() + "',NUMERTEL='"+ txtNumerTel.getText() + "',PESEL='"+ txtPesel.getText() + "',WIEK=" + txtWiek.getText() + ",UWAGI='"+ txtUwagi.getText() + "',PLEC='" + cmbPlec.getSelectedItem() + "',GK='"+ cmbGrupaKrwi.getSelectedItem() + "',ADRES='" + txtAdres.getText() + "' where PACJENTID='" + txtIDPacjenta.getText() + "'";

            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Nadpisano !","Powodzenie",JOptionPane.INFORMATION_MESSAGE);
            btnNadpisz.setEnabled(false);

        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);
        }  
    }//GEN-LAST:event_btnNadpiszActionPerformed

    private void txtPeselKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPeselKeyTyped
     char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
    }//GEN-LAST:event_txtPeselKeyTyped

    private void txtWiekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWiekKeyTyped
     char c=evt.getKeyChar();
      if (!(Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))){
          getToolkit().beep();
          evt.consume();
    }          
    }//GEN-LAST:event_txtWiekKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacjent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacjent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacjent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacjent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Pacjent().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnNadpisz;
    private javax.swing.JButton btnNowy;
    private javax.swing.JButton btnPacjenci;
    public javax.swing.JButton btnUsun;
    public javax.swing.JButton btnZapisz;
    public javax.swing.JComboBox cmbGrupaKrwi;
    public javax.swing.JComboBox cmbPlec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtAdres;
    public javax.swing.JTextField txtIDPacjenta;
    public javax.swing.JTextField txtImie;
    public javax.swing.JTextField txtNazwisko;
    public javax.swing.JTextField txtNumerTel;
    public javax.swing.JTextField txtPesel;
    public javax.swing.JTextArea txtUwagi;
    public javax.swing.JTextField txtWiek;
    // End of variables declaration//GEN-END:variables
}
